" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
	syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
	filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
	source /etc/vim/vimrc.local
endif

"=========== By elechole

noremap <leader>f ]}v[{zf
noremap <leader><leader> zf%

"The screen will not be redwawn while excuting macros
set lazyredraw

"Directories for swp Files
"set backupdir=~/.vim_backup
"set directory=~/.vim_backup

map ,noi :set noai<CR>:set nocindent<CR>:set nosmartindent<CR>
map ,sei :set ai<CR>:set cindent<CR>:set smartindent<CR>

imap	<silent>	<C-T><C-T> <C-R>=strftime("%Y-%m-%d %T")<CR>

"	Tab control in VIM
"	gt : tabnext
"	gT : tabprevious
nmap	tn		:tabnew<CR>
nmap	tc		:tabclose<CR>
nmap	<TAB>	:tabnext<CR>
nmap	tp		:tabprevious<CR>

"	Vim 256 Color setting
set t_Co=256
set t_AB=[48;5;%dm
set t_AF=[38;5;%dm

set nocompatible
set nu
syntax on
set history=500
set nobackup
set hlsearch	"	Highlighting Search results
set showmode
set tabstop=4
set softtabstop=0
set shiftwidth=4
"set expandtab	"	Tab 입력을 space로.. Tab입력은 CTRL-V + Tab
set noexpandtab
set cindent
set cinoptions=g0,0,l1,t0
set autoindent
set smartindent
set bg=dark
"set bg=light
set backspace=indent,eol,start
set visualbell		"	Alert 음을 화면 깜박임으로 바꿔보여주기
set ffs=unix,dos,mac
set report=0		"	Threshold for reporting number of lines changed.
set ruler			"	cursor 위치 항상 보이기
set statusline=%<%n:\ %t\ (%f)\ ascii=%b\ %=[%{&ff}:%{&fenc}]%h%r%w%y%m\ %-20(col:\ %c%V\ line:\ %l/%L%)\ (%P)	" 상태표시줄 포맷팅
set laststatus=2	"	statusline 항상 켜기
set scrolloff=5
set sidescrolloff=5
set selection=exclusive		"	커서 위치 문자 선택에 미포함.
set ttyfast
"set whichwrap=h,l,<,>,[,]
"set wildmode=longest:full,full

"set exrc

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"set comments=sl:/*,mb:*,elx:*/
"	smartcase	소문자로 검색: 대소문자 구분없이 검색시
"				대문자 있으면: 대소문자 구분하여 검색

"set scs

se cursorline
autocmd InsertEnter * hi CursorLine term=none cterm=none ctermbg=17 guibg=#000060
autocmd InsertEnter * hi CursorColumn term=none cterm=none ctermbg=17 guibg=#000060
autocmd InsertLeave * hi CursorLine term=none cterm=none ctermbg=236 guibg=#303030
autocmd InsertLeave * hi CursorColumn term=none cterm=none ctermbg=236 guibg=#303030
autocmd VimEnter * hi CursorLine term=none cterm=none ctermbg=236 guibg=#303030
autocmd VimEnter * hi CursorColumn term=none cterm=none ctermbg=236 guibg=#303030

"============= ctag config ==============
set tags+=tags
set tags+=/usr/include/tags

"if has("autocmd")
	" When editing a file, always jump to the last cursor position
	"autocmd BufReadPost *
	"			\ if line("'\"") > 0 && line ("'\"") <= line("$") |
	"			\   exe "normal g'\"" |
	"			\ endif
"endif

"enable C++ line style comments
let c_cpp_comments = 0
"Do highlighting similarly to the C syntax file supplied with VIM
"let c_c_vim_compatible = 1
let c_gnu = 1
let c_C99 = 1
let c_syntax_for_h = 1

if has("gui_running")
	"set textwidth=80
	set guioptions-=T "remove Toolbar
	set guioptions+=b
	"set guioptions-=m "remove memu bar
	"set guioptions+=b "bottom scroll bar 
	"set nowrap 
	set wrap 

	"set gfn=Courier\ New:h10
	map <A-SPACE> :simalt~x <CR>
	map <C-SPACE> :simalt~r <CR>

	winp 0 0
	win 130 50
	"set scrolloff=3
endif

set gfn=LucidaSansTypewriter\ 9
set fileencoding=utf-8
set fileencodings=utf-8,cp949,euc-kr

behave xterm

colorscheme torte

highlight Cursor guibg=Red guifg=Black ctermbg=Red ctermfg=Black
highlight CursorIM guibg=Blue guifg=NONE ctermbg=Blue ctermfg=NONE

set csprg=/usr/bin/cscope
set csto=0
set cst
set nocsverb
if filereadable("cscope.out")
	"cscope add cscope.out	"	add from plugins/cscope_maps.vim
else
	if $ANDROID_BUILD_TOP !=""
		"This assumes you have sourced the Android build environment
		cscope add $ANDROID_BUILD_TOP/cscope.out
	else
		"Or, you can point to your android source directory in $ANDROID_DIR 
		cscope add $ANDROID_DIR/cscope.out
	endif
endif
"set csverb

" Trailing White-spaces....
highlight TrailingWhiteSpace guibg=#505050 ctermbg=DarkGray
match TrailingWhiteSpace /\s\+$/
autocmd InsertEnter * match TrailingWhiteSpace /\s\+\%#\@<!$/
autocmd InsertLeave * match TrailingWhiteSpace /\s\+$/
autocmd WinEnter * match TrailingWhiteSpace /\s\+$/
